approve_by_comment: true
approve_regex: '^:\+1:'
reject_regex: '^:\-1:'
reset_on_push: true
author_approval: ignored
reviewers:
    -
        name: maintainers
        required: 2
        members:
            - fwbrasil
            - godenji
            - gustavoamigo
            - jilen
            - lvicentesanchez
        conditions:
            branches:
                - master